spring.application.name=jbdl95IocDi


server.port=8081

#logging.level.root=debug

test.int.value=100
test.string.value=apple
test.float.value=40.26

#person object - com.example.jbdl95iocdi.Person@6f3e19b3